= Apk Backdoor
TriSec
v1.0.0, 24 febbraio 2020: Stesura della documentazione
:toc: left
:toclevels: 4
:doctype: book
:sectnums:
:partnums:
:sectnumsdepth: 5
:xrefstyle: short
:source-highlighter: rouge
:icons: font
:lang: it
:title-logo-image: image:images/trisec_and_apkbackdoor.svg[]
include::locale/attributes.adoc[]

== Introduzione

*TriSec* è un gruppo di studenti al terzo anno del Corso di Laurea in
Informatica e Comunicazione Digitale dell'Università degli Studi di Bari "`A.
Moro`", composto da Andrea *Esposito*, Alessandro *Annese* e Graziano *Montanaro*.

Il nome del team deriva dalla condensazione del prefisso greco "`tri`" (tre,
come i componenti del gruppo) e "`Sec`" (da "`Security`").

.Logo di Apk Backdoor
image::images/apk_backdoor.svg[Apk Backdoor]

Il progetto, "`**Apk Backdoor**`" rappresenta uno sviluppo di un meta-attacco,
ovverosia uno sviluppo di una intera classe di attacchi. Tali attacchi sono
accumunati da tutte le fasi della killchain fatta eccezione per la fase di
azione (che varia in base agli obiettivi specifici). L'intera classe di attacchi
si basa sulla introduzione di una _backdoor_ ("`porta sul retro`") all'interno
di APK validi e funzionanti.

=== Contesto

Si è deciso di realizzare una intera classe di attacchi aventi l'obiettivo di
ottenere l'accesso a un sistema Android, uno dei sistemi operativi mobile più
diffusi.

Nello specifico, si realizzerà un _tool_ che consenta l'automatizzazione
dell'iniezione di codice malevole all'interno di un APK funzionante. Da qui,
l'obiettivo è quello di ottenere il controllo remoto del dispositivo mobile,
spianando la strada a qualsiasi tipo di obiettivo l'attaccante possa voler
raggiungere (per esempio, furto di dati sensibili o ricatti).

=== Scenario

Al giorno d'oggi, la maggioranza delle persone utilizzano applicazioni per
l'ascolto di musica on-demand online. Esempi di questi sistemi sono Spotify,
Amazon Music, iTunes, Google Music, ecc.

Molti di questi sistemi prevedono un sistema di abbonamento mensile per
permettere agli utenti di usufruire dei loro servizi. Tuttavia, una gran parte
degli utenti non è disposta a pagare per servizi digitali e quindi le aziende
forniscono una versione "`limitata`" dei loro servizi gratuitamente.

Ma queste limitazioni non sono spesso accettate da tutti: molti utenti
preferiscono, infatti, "`crackare`" l'applicazione in modo da poterla utilizzare
senza alcun tipo di limitazione. Ed è in questo scenario che l'attacco si
colloca: gli attaccanti hanno l'obiettivo di fornire una crack corrotta agli
utenti che, una volta installata, fornisca una porta di accesso al sistema
spianando la strada a furti di dati o altri danni.

== Killchain

.Killchain
[cols="<.^,^.^h,>.^",options="header"]
|===
|Red Team|Phase|Blue Team
|Individuazione del mezzo di trasmisisone (app)|Reconnaissance|Prevenire l'installazione di applicazioni da fonti sconosciute
|Preparazione dell'applicazione modificata|Weaponization|Implementare restrizioni sull'attivazione di modalità non consone all'utilizzo del dispositivo
|Preparazione dell'esca e condivisione del link di download|Delivery|Visitare solo siti internet attendibili
|Autoesecuzione del payload|Exploit|Utilizzare antivirus sempre aggiornati
|Installazione da parte dell'utente|Installation|Controllare sempre le autorizzazioni richieste dalle applicazioni
|Attivazione della backdoor|Command & Control|Effettuare scansioni periodiche del sistema
|Sfruttamento della backdoor|Action|Rimuovere l'applicazione malevola
|===

[#reconnaissance]
=== Reconnaissance

La fase di "ricognizione" è una delle fasi principali di tutti gli attacchi in
quanto dedicata alla raccolta delle informazioni sull'obiettivo e alla
successiva stesura del piano di azione (che determina quindi l'intero esito
dell'attacco). Allo stesso modo è importante questa fase per la difesa degli
assets in quanto impedire la ricognizione impedisce, di fatto, di strutturare un
attacco ben definito.

[#reconnaissance-red-team]
==== Red Team

include::red-team/reconnaissance.adoc[]

[#reconnaissance-blue-team]
==== Blue Team

include::blue-team/reconnaissance.adoc[]

[#weaponization]
=== Weaponization

Questa fase riguarda la preparazione del malware vero e proprio.

[#weaponization-red-team]
==== Red Team

include::red-team/weaponization.adoc[]

[#weaponization-blue-team]
==== Blue Team

include::blue-team/weaponization.adoc[]

[#delivery]
=== Delivery

In questa fase avviene la "`consegna`" del malware creato precedentemente.

[#delivery-red-team]
==== Red Team

include::red-team/delivery.adoc[]

[#delivery-blue-team]
==== Blue Team

include::blue-team/delivery.adoc[]

[#exploit]
=== Exploit

Fase in cui l'attaccante utilizza un software inviando comandi per far compiere azioni malevoli

[#exploit-red-team]
==== Red Team

include::red-team/exploit.adoc[]

[#exploit-blue-team]
==== Blue Team

include::blue-team/exploit.adoc[]

[#installation]
=== Installation

Dopo aver compromesso il sistema, l'attaccante installa il malware necessario a compiere le azioni malevoli.

[#installation-red-team]
==== Red Team

include::red-team/installation.adoc[]

[#installation-blue-team]
==== Blue Team

include::blue-team/installation.adoc[]

[#command-and-control]
=== Command & Control

In questa fase l'attaccante assume il controllo da remoto del sistema compromesso.

[#command-and-control-red-team]
==== Red Team

include::red-team/command-and-control.adoc[]

[#command-and-control-blue-team]
==== Blue Team

include::blue-team/command-and-control.adoc[]

[#action]
=== Action

Gli attaccanti eseguono le operazioni a utili al proprio scopo e/o sferrano attacchi ad altri dispositivi di rete.

[#action-red-team]
==== Red Team

include::red-team/action.adoc[]

[#action-blue-team]
==== Blue Team

include::blue-team/action.adoc[]


include::red-team/appendix-code.adoc[]

[bibliography]
== Riferimenti

- [[[spotify-users]]] Matthew De Silva, _28 ottobre 2019_, su "`Quarz`". 
  URL: https://qz.com/1736762/spotify-grows-monthly-active-users-and-turns-profit-shares-jump-15-percent/ (visitato il 20 febbraio 2020)
- [[[spotify-pirated]]] Rolling Stone, _4 agosto 2019_, su "`RollingStone`".
  URL: https://www.rollingstone.it/musica/news-musica/spotify-raggiunge-quota-232-milioni-di-utenti-ma-solo-la-meta-paga/471803/ (visitato il 23 febbraio 2020)
