#!/usr/bin/env ruby

require "asciidoctor"
require_relative "./ruby/asciidoctor-pdf-extension"

task :asciidoc do
  # Asciidoctor.convert_file "content.adoc", backend: "docbook5", safe: :unsafe
  Asciidoctor.convert_file "content.adoc", backend: "html", safe: :unsafe, to_file: 'index.html'
  Asciidoctor.convert_file "content.adoc", backend: "pdf", attributes: { "lang" => "it", "pdf-theme" => "book", "pdf-themesdir" => "./themes", "media" => "prepress" }, safe: :unsafe, to_file: 'CyberSecurity.pdf'
end

task :default => :asciidoc
# do
#   command = 'pandoc -f docbook .\content.xml -t latex -o content.tex --top-level-division=chapter --filter pandoc-citeproc --biblatex'
#   puts command
#   `#{command}`

#   (1..3).each do |i|
#     if i == 2
#       command = "biber CyberSecurity"
#       puts command
#       `#{command}`
#     end
#     command = "pdflatex --interaction=nonstopmode CyberSecurity.tex"
#     puts command
#     `#{command}`
#   end
# end
